config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#home"

  get 'about', to: 'pages#about'

  resources :users, only: [:show]

  resources :appointments
  resources :user_steps
  resources :account_creations
  resources :accounts do
    get :switch
  end

  namespace :admin do
    resources :users, only: [:index]

    resources :appointments do
      collection do
          get :confirmed_index
      end

      member do
        get :confirm
        get :cancel
        get :upload_result
        patch :assign_doctor
        put :upload
      end
    end
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :user
	belongs_to :account
	belongs_to :doctor, class_name: 'User', foreign_key: 'doctor_id'
	has_many :notifications
	has_many :appointments_doctors
	has_many :doctors, through: :appointments_doctors, class_name: "User", foreign_key: 'doctor_id'

	has_one :result

	after_save :create_result

	def create_result
		Result.create(appointment: self)
	end

end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < AdminController
	def index
		@appointments = Appointment.all
	end

	def confirmed_index
		@appointments = Appointment.where(confirmed: true)
	end

	def show
		@appointment = Appointment.find(params[:id])
	end

	def confirm
		@appointment = Appointment.find(params[:id])

		if @appointment.update_attributes(confirmed: true)
			flash[:notice] = "Appointment number #{@appointment.id} confirmed."

		    redirect_to admin_appointments_path
	    else
	    	flash[:alert] = 'Error occured.'
	    end	
	end

	def cancel
		@appointment = Appointment.find(params[:id])

		if @appointment.update_attributes(confirmed: false)
		    flash[:notice] = "Appointment number #{@appointment.id} canceled."

		    redirect_to admin_appointments_path
		else
		    flash[:alert] = 'Error occured.'
		end
	end

	def upload_result
		@appointment = Appointment.find(params[:id])
		@result = @appointment.result || Result.create(appointment: @appointment)
	end

	def upload
		@appointment = Appointment.find(params[:id])
		@result = @appointment.result
		@result.update(result_params)

		redirect_to [:admin, @appointment]
	end

	def assign_doctor
		@appointment = Appointment.find(params[:id])
		@appointment.update_attributes(appointment_params)
		# Send a notification to the android device
		puts @appointment.doctors.collect(&:id)
		@appointment.doctors.each do |doctor|
			@appointment.notifications.create(user_id: @appointment.user_id, doctor_id: doctor.id)
		end
		redirect_to [:admin, @appointment]
	end

	private

	def result_params
		params.require(:result).permit(:document)
	end

	def appointment_params
		params.permit(doctor_ids: [])
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	def index
		@appointments = Appointment.where(user: current_user)
	end

	def new
	  @appointment = Appointment.new

	  @users = [current_user] + User.with_role('doctor')
	  @users = @users.select { |user| user.longitude.present? && user.latitude.present? }

	  @hash = Gmaps4rails.build_markers(@users) do |user, marker|
  		marker.lat user.latitude
  		marker.lng user.longitude
  		if user.has_role? ('doctor')
  			marker.picture({
  		  		"url" => "http://www.fancyicons.com/free-icons/103/pretty-office-6/png/32/doctor_32.png",
          		"width" =>  32,
          		"height" => 32
  			})

  		  @infowindow = "<b style='font-size: 20px;'>#{user.name}</b><br>"

  		  if user.specialization.present?
  		  	@infowindow += "<p style='font-size: 15px;'>#{user.specialization}<p>"
  		  end

  		  marker.infowindow @infowindow
  		end

  		if user == current_user
  			marker.infowindow 'You'
  		end
      end
	end

	def show
		@appointment = Appointment.find(params[:id])
	end

	def create
		@appointment = Appointment.new(appointment_params)
		@appointment.user = current_user

		if @appointment.save
			if current_user.accounts.present?
				flash[:notice] = "Appointment for #{@appointment.account.name} created. Time: #{@appointment.time}. Pending Confirmation."
	    	else
	    		flash[:notice] = "Appointment for #{current_user.name} created. Time: #{@appointment.time}. Pending Confirmation."
	    	end
	    end

	    sign_out current_user

	    redirect_to root_path
	end

	private

	def appointment_params
		params.require(:appointment).permit(:time, :reason, :account_id)
	end
end

app/helpers/admin/appointments_helper.rb
module Admin::AppointmentsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/admin/appointments/confirmed_index.html.erb
<% @appointments.each do |appointment| %>
  <h3><%= appointment.id %><h3>
  <%= appointment.time %>

  <%= link_to appointment.user.name, user_path(appointment.user) %>

  <%= link_to 'Confirm', confirm_admin_appointment_path(appointment) unless appointment.confirmed %></div>

  <%= link_to 'Cancel', cancel_admin_appointment_path(appointment) %>

   	<%= link_to 'Upload result', upload_result_admin_appointment_path(appointment) %>

  <hr>
<% end %>

app/views/admin/appointments/index.html.erb
<% @appointments.each do |appointment| %>

  <h3><%= appointment.id %><h3>
  <%= appointment.time %>

  <%= link_to appointment.user.name, user_path(appointment.user) %>

  <%= link_to 'Confirm', confirm_admin_appointment_path(appointment) unless appointment.confirmed %></div>

  <%= link_to 'Cancel', cancel_admin_appointment_path(appointment) %>

   	<%= link_to 'Upload result', upload_result_admin_appointment_path(appointment) %>

   	<%= form_for appointment, url: assign_doctor_admin_appointment_path(appointment) do |f| %>
      <% User.doctors.each do |d| %>
   		  <%= check_box_tag "doctor_ids[]", d.id, appointment.doctor_ids.include?(d.id) %><%= d.name %><br/>
  	  <% end %>
      <%= f.submit %>
    <% end %>

  <hr>
<% end %>

app/views/admin/appointments/show.html.erb
<%= image_tag @appointment.result.document.url %>
<% @appointment.doctors.each do |doctor| %>
	<%= doctor.name %><br/>
<% end %>

app/views/admin/appointments/upload_result.html.erb
<%= simple_form_for @result, url: upload_admin_appointment_path, method: :put, html: { multipart: true } do |form| %>
  <%= form.input :document, as: :file %>

  <%= form.submit %>
<% end %>